# 用户程序名称
name = "lmbench_bin_ubuntu2404"
# 版本号
version = "3.0"
# 用户程序描述信息
description = "LMbench - Tools for Performance Analysis from Ubuntu 24.04"
# （可选）默认: false 是否只构建一次，如果为true，DADK会在构建成功后，将构建结果缓存起来，下次构建时，直接使用缓存的构建结果
build-once = false
#  (可选) 默认: false 是否只安装一次，如果为true，DADK会在安装成功后，不再重复安装
install-once = false
# 目标架构
# 可选值："x86_64", "aarch64", "riscv64", "loongarch64"
target-arch = ["x86_64"]
# 任务源
[task-source]
# 构建类型
# 可选值："build-from-source", "install-from-prebuilt"
type = "install-from-prebuilt"
# 构建来源
# "build_from_source" 可选值："git", "local", "archive"
# "install_from_prebuilt" 可选值："local", "archive"
source = "archive"
# 本地目录路径 - 指向已解压的 sysroot 目录
source-path = "https://mirrors.dragonos.org.cn/pub/third_party/lmbench/lmbench-ubuntu2404-202511301014-36c2fb2d084343e098b5e343576d4fc0.tar.xz"
archive-rootdir = "sysroot/"

[build]

# 安装相关信息
[install]
# （可选）安装到DragonOS的路径
in-dragonos-path = "/"
# 清除相关信息
[clean]
# （可选）清除命令
clean-command = ""
# 依赖项
[[depends]]
name = "glibc_bin_ubuntu2404"
version = "2.39"

# （可选）环境变量
# 注意：如果没有环境变量，忽略此项，不允许只留一个[[envs]]
