[package]
name = "test_unix_stream_socket"
version = "0.1.0"
edition = "2021"
description = "test for unix stream socket"
authors = [ "smallcjy <2628035541@qq.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]