[package]
name = "syscall_ebpf-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { git = "https://git.mirrors.dragonos.org.cn/DragonOS-Community/tiny-aya.git", rev = "9632e57", optional = true }

[lib]
path = "src/lib.rs"
